### ISSUE TITLE
Batch renaming does not work

### ISSUE THREAD

**Issue by Xananax** [trentinfrederick/item-panel#4] opened 2015-12-29 22:58 UTC
Reproduce: Select things (meshes, bones...). Batch rename. Test any setting. Press "ok", get "0 datablock renamed". Nothing I did made it work. I'm not sure if I'm doing something wrong.

Blender 2.76b on Arch Linux

**Comment by trentinfrederick** [comment] 2015-12-30 04:15
Can't reproduce, everything works on my end, try removing the item_panel add-on then reinstalling, make sure that the icons that represent the datablocks you want to rename are also toggled on in the batch name operator, i.e. bone icon or object icon, etc..

By default all these options are off, so nothing happens, you must make sure that the appropriate icons are turned on, the one that carries the same symbol in blender. also the tool-tips will tell you some more information.

does the terminal return any errors?

**Comment by trentinfrederick** [comment] 2015-12-30 04:30
Closing this issue for now, if you still cannot get it to work let me know here.

**Closed by trentinfrederick** 2015-12-30 04:30 UTC

**Comment by Xananax** [comment] 2015-12-30 17:55
Right, I was just being stupid, it works. Sorry, and have a good day :)

Thanks for a much needed plugin

**Comment by trentinfrederick** [comment] 2015-12-30 18:13
Not a problem, I get it a lot, once you get used to using it I hope you can appreciate the approach I took in the interface design :)
